// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuss_etvXgs47myAtrbTPQqGYqRFqW-uY',
    appId: '1:412242404290:web:6731ec3329e5a5049bec5b',
    messagingSenderId: '412242404290',
    projectId: 'shoppingapp-71f14',
    authDomain: 'shoppingapp-71f14.firebaseapp.com',
    storageBucket: 'shoppingapp-71f14.appspot.com',
    measurementId: 'G-SZD9N17CPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9IIgFn749mffEkF6ExGBT1Qp5jzV76rU',
    appId: '1:412242404290:android:42efa0ab2c19ef139bec5b',
    messagingSenderId: '412242404290',
    projectId: 'shoppingapp-71f14',
    storageBucket: 'shoppingapp-71f14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRBBu-q2szXdUx2lCiRasDk02KKtSWwW4',
    appId: '1:412242404290:ios:d6c0caeba23c0d9c9bec5b',
    messagingSenderId: '412242404290',
    projectId: 'shoppingapp-71f14',
    storageBucket: 'shoppingapp-71f14.appspot.com',
    iosBundleId: 'com.example.finalExamAd',
  );
}
